"""
models/match.py
───────────────
Pydantic model representing the result of matching a candidate against a job posting.
"""

from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field

from .candidate import CandidateProfile
from .job import JobPosting


class MatchResult(BaseModel):
    """
    The output of comparing a CandidateProfile against a JobPosting.

    Produced by services/matcher.py (semantic score) and optionally enriched
    by agents/match_explainer.py (LLM explanation).
    """

    # ── References ─────────────────────────────────────────────────────────────
    job: JobPosting = Field(..., description="The job posting that was matched")
    # Note: We don't embed the full candidate here to avoid duplication.
    # The caller always has the CandidateProfile in context.

    # ── Score ──────────────────────────────────────────────────────────────────
    semantic_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Cosine similarity between candidate embedding and job embedding (0–1)",
    )
    composite_score: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Weighted blend of semantic + skill overlap scores",
    )
    rank: Optional[int] = Field(
        None, description="Position in the ranked results list (1 = best)"
    )

    # ── Skill analysis ─────────────────────────────────────────────────────────
    matched_skills: List[str] = Field(
        default_factory=list,
        description="Skills the candidate has that the job requires",
    )
    missing_skills: List[str] = Field(
        default_factory=list,
        description="Required job skills the candidate appears to lack",
    )
    bonus_skills: List[str] = Field(
        default_factory=list,
        description="Candidate skills not required but potentially valuable",
    )
    skill_overlap_ratio: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="matched_skills / total_required_skills",
    )

    # ── LLM explanation ────────────────────────────────────────────────────────
    explanation: Optional[str] = Field(
        None,
        description="Human-readable match explanation generated by the LLM (Phase 5)",
    )
    recommendation: Optional[str] = Field(
        None,
        description="Brief LLM recommendation: 'Strong Match', 'Good Fit', 'Reach', 'Skip'",
    )

    # ── Convenience properties ─────────────────────────────────────────────────
    @property
    def display_score(self) -> float:
        """The score to show in the UI: composite if available, else semantic."""
        return self.composite_score if self.composite_score is not None else self.semantic_score

    @property
    def display_score_pct(self) -> str:
        """Formatted percentage string for display."""
        return f"{self.display_score * 100:.0f}%"

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "semantic_score": 0.87,
                "composite_score": 0.84,
                "rank": 1,
                "matched_skills": ["Python", "FastAPI", "PostgreSQL"],
                "missing_skills": ["Kubernetes", "Go"],
                "skill_overlap_ratio": 0.75,
                "explanation": "Strong alignment on backend Python skills...",
                "recommendation": "Strong Match",
            }
        }
    )
